### ISSUE TITLE
NotSupportedException: Fluent methods may not be invoked on a Query created via CloudTable.CreateQuery

### ISSUE THREAD

**Issue by moberg** [madd0/AzureStorageDriver#10]
I've added a new LinqPad connection and i can see the tables i've got stored. But when I try to fetch some data, for example:

  data.Take (100)

I get the following exception:
  NotSupportedException: Fluent methods may not be invoked on a Query created via CloudTable.CreateQuery

**Comment by madd0** [comment]
Hi @moberg,

This is unfortunately a limitation of the Azure SDK. I privileged query syntax over fluent methods because that is my need. So a query like:

    from d in data
    select d

should work fine.

You can still use the following syntaxes though, to use fluent methods:

    (from d in data
     select d).Take(100)

or

    data.AsQueryable().Take(100)
