### ISSUE TITLE
Azure Table Query doesn't show all properties when new properties are added

### ISSUE THREAD

**Issue by idisciple** [madd0/AzureStorageDriver#16]
I recently added new properties to an Azure Table. i.e. Old table entries had EventId, EventValue. I added Platform and ContentId values to new rows.

When I run a Linq query in linqpad, it doesn't show the new values. I was able to verify that they are there using Visual Studio. Is there something being cached that is preventing the new data from showing up in the query?

Here's an example query i'm using.

from c in ContentConsumptionEventLog
where c.EventTimestamp > DateTime.Parse("04-25-2018 13:00") 
select c

**Comment by madd0** [comment]
The table structure is indeed cached. You can right-click on the connection and select Refresh. This should re-scan your tables and attempt to detect the new structure. Keep in mind that, to detect the table structure, the driver will only scan the first 100 rows by default. You can change this in the Advanced section of the connection properties if needed.

**Comment by idisciple** [comment]
ok.  in this case there are thousands of records before the structure changed.  It doesn't look like you can specify starting at the end.  Thanks for the quick response.
