### ISSUE TITLE
Any change this is going to be updated for LINQPad 6?

### ISSUE THREAD

**Issue by rluiten** [madd0/AzureStorageDriver#18]
I am quite new to linqpad, and this driver seems terribly useful to me.

**Comment by madd0** [comment]
I'm almost done. Hopefully this weekend ;)
I already updated [a prelease version](https://www.nuget.org/packages/Madd0.AzureStorageDriver/) to Nuget if you're impatient

**Comment by rluiten** [comment]
That's great to hear :).
I might have a look at the prerelease.

**Comment by rluiten** [comment]
So far your preview is working well, awesome!

**Comment by madd0** [comment]
I have published a new version to Nuget: https://www.nuget.org/packages/Madd0.AzureStorageDriver/
I called it 2.0.0 and removed the prerelease tag.
Let me know if you find any issues ;)
