### ISSUE TITLE
I might have the wrong expectations is it possible save changes to table storage not just query?

### ISSUE THREAD

**Issue by rluiten** [madd0/AzureStorageDriver#21]
Cheers, for any suggestion.
We may need to look at a console app if it can't.

**Comment by madd0** [comment]
Hi,

The driver includes pretty recent versions of Microsoft's *Azure Cosmos DB Table APIs*, so anything you wanted to do with a console app can be done straight from LinqPad too.

- LINQPad 6 plugin uses Microsoft.Azure.Cosmos.Table 1.0.5
- LINQPad 5 plugin uses Microsoft.Azure.CosmosDB.Table 2.1.2

Once you have associated an Azure Table Storage connection to your query, you can use `this.TableClient` to get a `CloudTableClient` instance and, for any detected tables, you can use `this.MyTestTable.CloudTable` to get a `CloudTable` instance.

I think that with those two, you can do pretty much anything. If you create any new tables in your script, all you have to do is refresh the connection for them to be detected.

**Comment by rluiten** [comment]
Sorry for my tardy response, this helped us.
Thanks.

**Comment by rs38** [comment]
@madd0 
I try to follow your hint:
with Linqpad6 I am unable to retrieve a TableClient from `this´ context to start with.
the only object I can see is a `System.Data.SqlClient.SqlConnection`.

is there a way to reuse the associated connection to add rows?

**Comment by madd0** [comment]
@rs38 are you sure that you have selected the correct Connection?

This is what it looks like when you're using a connection created by the plugin:

![image](https://user-images.githubusercontent.com/313466/130487068-5b583e8a-416a-47e5-9ca7-7f159894921d.png)

**Comment by rs38** [comment]
I though I was sure :)
Now it's clear, it must have been sth. very stupid like that...
thanks a lot, I should have asked earlier!

![image](https://user-images.githubusercontent.com/12622612/130522046-7b1f1a2e-4d73-4d96-ba9a-3075ad28764d.png)
