### ISSUE TITLE
Microsoft.Azure.Cosmos.Table 1.0.5 brings in Newtonsoft 10.x, and Linqpad 7 pops up a Warning

### ISSUE THREAD

**Issue by Noctis-** [madd0/AzureStorageDriver#22]
The specific warning is : 

```
Warning: LINQPad has identified the following vulnerabilties in NuGet package Newtonsoft.Json 10.0.2:

Level 2 (High): https://github.com/advisories/GHSA-5crp-9r3c-p9vr
Try updating NuGet packages to latest. You can suppress this warning in Edit | Preferences > Advanced > Execution.
```

I've tried pulling the code and updating newtonsoft to version 13, but, i have no idea how to build / publish / test this :(

There's a newer version of the `Microsoft.Azure.Cosmos.Table` (1.0.8) , which it fails to install (doubt it'll fix the issue though, as that vulnerability was fixed in the newtosoft v 13, which was released in Mach '21, and the 1.0.8 was done in august '20).

The whole `Microsoft.Azure.Cosmos.Table` is deprecated as well ... 
not sure if it's an easy fix, or worth fixing, but figured i'll post it in case you do want to give it a go .

(oh, and cheers for you work BTW, regardless 🙏 )

**Comment by madd0** [comment]
@Noctis- thanks for the heads up. I'll look into it.

**Comment by Noctis-** [comment]
Legend. Cheers

**Comment by Noctis-** [comment]
Any thoughts / updates ? (asking from pure curiosity, as i've seen something about forcing a newer version of a package by including it in the csproj. I tried doing it, but i have no idea how to make linqpad use the dll, as it only accepts linqpad drivers and stuff)

**Comment by Noctis-** [comment]
No worries, thanks for the update!

**Comment by madd0** [comment]
v2.1.2 has been published to Nuget, it includes the latest version of Json.Net

Thanks

**Comment by Noctis-** [comment]
Thank you!
